# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ringbinder < Formula
  desc "Scan, OCR, and search local PDFs and images"
  homepage "https://github.com/maxim/ringbinder"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/maxim/ringbinder/releases/download/v0.1.0/ringbinder_0.1.0_darwin_amd64.tar.gz"
      sha256 "e676f37d5d7c02768ea66729b732614781bcfe4c31d86530cc692ace5eab92c6"

      define_method(:install) do
        bin.install "ringbinder"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/maxim/ringbinder/releases/download/v0.1.0/ringbinder_0.1.0_darwin_arm64.tar.gz"
      sha256 "d44ebd840b4b8001edc3b86a47b79d59c81b0c935975b90a65e50de101a319b0"

      define_method(:install) do
        bin.install "ringbinder"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/maxim/ringbinder/releases/download/v0.1.0/ringbinder_0.1.0_linux_amd64.tar.gz"
      sha256 "62216ed37376f8a997a4c2429fd663295090e085b74725e002d411ce411d23bd"
      define_method(:install) do
        bin.install "ringbinder"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/maxim/ringbinder/releases/download/v0.1.0/ringbinder_0.1.0_linux_arm64.tar.gz"
      sha256 "3c4853f6a93afaf8b0e9edb7f10042762962a0cf3c55e29e6f2b901622829ff2"
      define_method(:install) do
        bin.install "ringbinder"
      end
    end
  end

  test do
    assert_equal "ringbinder version v#{version}\n", shell_output("#{bin}/ringbinder --version")
    # The explicit testpath database isolates this test from user config, state, and API credentials.
    output = shell_output("#{bin}/ringbinder --database #{testpath}/ringbinder.db cost")
    assert_match "No documents pending OCR.", output
    assert_path_exists testpath/"ringbinder.db"
  end
end
